on:
  push:
    branches: [master]
  #schedule:
  #  - cron: '0 0 * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update versions
        run: |
          if version=$(curl -s https://api.github.com/repos/sandpolis/com.sandpolis.agent.kilo/tags | jq '.[0] | .name' | tr -d 'v"'); then
            sed -i "s/pkgver=.*$/pkgver=${version}/" PKGBUILD
            sed -i "s/pkgver =.*$/pkgver = ${version}/" .SRCINFO
          fi

      - name: Commit changes
        uses: EndBug/add-and-commit@v7

  mirror:
    runs-on: ubuntu-latest
    needs: refresh
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ssh://aur.archlinux.org/sandpolis-agent.git
          ssh_username:
            aur
          ssh_private_key:
            ${{ secrets.AUR_SSH_PRIVATE_KEY }}
