on:
  push:
    branches: [master]
  #schedule:
  #  - cron: '0 0 * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'sandpolis/com.sandpolis.agent.kilo'
          path: 'target'
          fetch-depth: 0

      - name: Update versions
        run: |
          sed -i "s/pkgver=.*$/pkgver=$(cd ${GITHUB_WORKSPACE}/target && git describe --tags | tr -d 'v')/" PKGBUILD
          sed -i "s/pkgver =.*$/pkgver = $(cd ${GITHUB_WORKSPACE}/target && git describe --tags | tr -d 'v')/" .SRCINFO

      - name: Commit changes
        uses: EndBug/add-and-commit@v7

  mirror:
    runs-on: ubuntu-latest
    needs: refresh
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ssh://aur.archlinux.org/sandpolis-agent.git
          ssh_username:
            aur
          ssh_private_key:
            ${{ secrets.AUR_SSH_PRIVATE_KEY }}
